apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- marvel_deploy.yaml
- mongodbcommunity_cr.yaml
- job.yaml
- ondat_sc.yaml
- marvel_svc.yaml
patches:
- target:
    kind: StorageClass
    name: ondat-replicated
  patch: |-
    - op: replace
      path: /metadata/name
      value: ondat-prod
resources:
- ../../base
configMapGenerator:
- name: mongo-config
  literals:
  - MONGO_SEED0=mongodb-0.mongodb.default.svc.cluster.local
  - MONGO_SEED1=mongodb-1.mongodb.default.svc.cluster.local
  - MONGO_SEED2=mongodb-2.mongodb.default.svc.cluster.local
  - OFFSET=600
  - MONGO_USERNAME=admin
secretGenerator:
- name: admin-password
  literals:
  - password=mongo
configurations:
- name_reference.yaml