apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- ondat_local_storage_class.yaml
- marvel_deployment_replicas.yaml
- mongo_storage_class.yaml
- no-storageclass.yaml
resources:
- ../../base
