apiVersion: apps/v1
kind: Deployment
metadata:
  name: marvel-frontend
  namespace: default
spec:
  #local development environment requires 2 replicas
  replicas: 2
  template:
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: mongo-config
          - secretRef:
              name: admin-password
          name: flask-marvel