apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  version: "5.0.5"
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: admin-password
      scramCredentialsSecretName: admin
      roles:
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
  statefulSet:
      spec:
          # Specifies a size for the data volume different from the default 10Gi
        volumeClaimTemplates:
          - metadata:
              name: data-volume
            spec:
              storageClassName: "ondat-prod"
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 50Gi
          - metadata:
              name: logs-volume
            spec:
              storageClassName: "ondat-prod"
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 1Gi
