apiVersion: batch/v1
kind: Job
metadata:
  name: add-data-to-mongodb
spec:
  template:
    spec:
      containers:
      #ADD THE ENV SECTION TO CONFIGURE THE JOB PROCESS
      #AND SET THE TARGET DATABASE INSTANCE
      - image: vfiftyfive/marvel_init_db
        name: add-data-to-mongodb
      restartPolicy: Never
  backoffLimit: 10

