apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: add-data-to-mongodb
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      #ADD THE ENV SECTION TO CONFIGURE THE JOB PROCESS
      #AND SET THE TARGET DATABASE INSTANCE
      - env:
        - name: MONGO_HOST
          value: mongodb-0.mongodb.default.svc.cluster.local
        - name: OFFSET
          value: "600"
        image: vfiftyfive/marvel_init_db
        name: add-data-to-mongodb
        resources: {}
      restartPolicy: Never
  backoffLimit: 10
status: {}
