apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ondat_sc.yaml
- mongodbcommunity_cr.yaml
- marvel_deploy.yaml
- marvel_svc.yaml
- job.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
- service_account_database.yaml
- role_binding_database.yaml
- role_database.yaml
