apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  statefulSet:
      spec:
          # Name for the service object created by the operator
        serviceName: mongodb
        selector: {}
          # Specifies a size for the data volume different from the default 10Gi
        volumeClaimTemplates:
          - metadata:
              name: data-volume
            spec:
              storageClassName: "default"
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 1Gi