apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ondat-replicated
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageos
parameters:
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/secret-name: storageos-api
  csi.storage.k8s.io/secret-namespace: storageos
provisioner: csi.storageos.com
reclaimPolicy: Delete
volumeBindingMode: Immediate