apiVersion: batch/v1
kind: Job
metadata:
  name: add-data-to-mongodb
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: mongo-config
        name: add-data-to-mongodb