apiVersion: batch/v1
kind: Job
metadata:
  name: add-data-to-mongodb
  namespace: dev
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: mongo-config
        - secretRef:
            name: admin-password
        name: add-data-to-mongodb