apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- ondat_sc.yaml
- marvel_deploy.yaml
- mongodbcommunity_cr.yaml
- mongodb_admin_secret.yaml
resources:
- ../../base
images:
- name: vfiftyfive/flask_marvel
  newTag: 1.0_test
