apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
  - name: vfiftyfive/flask_marvel
    newTag: "1.0_test"
patchesStrategicMerge:
- ondat_local_storage_class.yaml
- marvel_deployment_replicas.yaml
- mongo_storage_class.yaml
  
