apiVersion: apps/v1
kind: Deployment
metadata:
  name: marvel-frontend
spec:
  #local development environment requires 2 replicas
  replicas: 3
  template:
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: mongo-config
          - secretRef:
              name: admin-password
          name: flask-marvel