apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  version: "5.0.5"
  statefulSet:
      spec:
          # Specifies a size for the data volume different from the default 10Gi
        volumeClaimTemplates:
          - metadata:
              name: data-volume
            spec:
              storageClassName: "ondat-replicated"
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 1Gi
