apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ondat-replicated
provisioner: csi.storageos.com
allowVolumeExpansion: true
parameters:
  #local development environment requires 1 replica
  storageos.com/replicas: "1" # Labels allowed only when using CSI
  storageos.com/encryption: "true"
